#!/usr/bin/env python3
import sys
import os
from glob import glob

templates_dir = os.path.expanduser("~/Templates/html")

args = sys.argv[1:]
try:
  source, *targets = args
  if source[0] == "-":
    if source == "-l":
      templates = [x.replace(".html","") for x in glob(os.path.join(templates_dir,"*.html"))]
      templates = [x[len(templates_dir)+1:] for x in templates]
      print("\n".join(templates))
      exit(0)
    print(f"Unknown switch {source}")
    raise Exception("")
except Exception:
  print(f"{sys.argv[0]} <template> [file1 file2...]")
  exit(1)

try:
  template_fn = os.path.join(templates_dir,source) + ".html"
  template = open(template_fn).read()
except Exception:
  print(f"Failed to load template {source} from {template_fn}")
  exit(2)

if len(targets) > 0:
  for target in targets:
    try:
      if os.path.exists(target):
        print(f"Target {target} already exists")
        continue
      with open(target,"wt") as f:
        f.write(template)
        print(f"Written {target}")
    except Exception as e:
      print(f"Failed to write {target}: Exception {e}")
else:
  sys.stdout.write(template)
