#!/bin/bash
if [ -n "$WAYLAND_DISPLAY" ]; then
  paste() { wl-paste; }
elif [ -n "$DISPLAY" ]; then # X11
  paste() { xsel -o -b; }
elif [ -d "/Applications" ]; then # macos
  paste() { pbpaste; }
elif [ -d "/cygdrive/c/cygwin64" ]; then # cygwin
  paste() { cat /dev/clipboard; }
else
  echo "Cannot paste as not gui" 1>&2 
fi
if [ -n "$1" ]; then
  paste | tee "$1"
else
  paste
fi
