#!/bin/bash
for s; do
  if [[ "$s" =~ .mkv$ ]]; then
    if [ -f "$s" ]; then
      ffmpeg -i "$s" "${s%.*}.mp4"
    else
      echo "$s does not exist"
    fi
  else
    echo "$s is not a mkv"
  fi
done
