#!/usr/bin/expect
set timeout 5

set host "[lindex $argv 0]"
set tport "[lindex $argv 1]"
puts "tport '$tport'"
if { $tport == "" } {
  set tport 0
}
set port "[expr 7000 + $tport]"
set password "tree"

spawn telnet $host $port
expect "Password:"
send "$password\r"

expect "Welcome, Master"

interact
