#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import wave
import sys

args = sys.argv[1:]
if len(args) == 0:
    print("No files!")
    sys.exit(1)

for x in args:
    spf = wave.open(x,'r')

    #Extract Raw Audio from Wav File
    signal = spf.readframes(-1)
    signal = np.fromstring(signal, 'Int16')

    #If Stereo
    if spf.getnchannels() == 2:
        print('Just mono files')
        sys.exit(0)

    plt.figure(1)
    plt.title('Waveform {}'.format(x))
    plt.plot(signal)
