#!/bin/bash
if [ "$1" = "-w" ]; then
  watch -n1 "$0"
else
  N=$(grep ^processor /proc/cpuinfo | wc -l)
  cpupower -c "$(seq -s , 0 $((N-1)))" frequency-info | grep "current CPU.*Hz" | awk '{ print (NR-1) " " $4 " " $5 }'
fi
