#!/bin/bash
T="$(hms "$1")"
shift
if [ $# = 0 ]; then
  echo "nothing to do"
  echo "doevery timeInterval cmd args..."
  exit 1
fi
if (( T < 60 )); then
  echo "Minimum time is 60s"
  T=60
fi
echo Time $T
while true; do
  echo Doing: "$@"
  "$@" || { A="$?"; echo "Exiting due to nonzero return ($A) code from $1" ; exit $A; }
  sleepy "$T"
done
