#!/usr/bin/env python
import sys
from PySide6.QtWidgets import QApplication
from sleepqt import Countdown
from datetime import datetime

def parse_time(x):
  a = x.split(":")
  if len(a) < 2 or len(a) > 3:
    raise ValueError("Time should be in the format hh:mm or hh:mm:ss")
  if len(a) == 2:
    h,m = map(int,a)
    s = 0
  else:
    h,m,s = map(int,a)
  return (h,m,s)

def compute_secs_until(x):
  h,m,s = parse_time(x)
  now = datetime.now()
  h1 = now.hour
  m1 = now.minute
  s1 = now.second
  secs = 3600*h+60*m+s
  secs1 = 3600*h1+60*m1+s1
  dt = secs - secs1
  if dt < 0:
    dt += 24*3600
  return dt

def main():
  args = sys.argv[1:]

  if len(args) == 0:
    print(f"sleepyqt target-time(h:m:s)")
    exit(1)
  dt = compute_secs_until(args[0])
  t = int(datetime.now().timestamp())
  t0 = t+dt
  app = QApplication([])
  win = Countdown(t0)
  win.go()
  try:
    exit(app.exec())
  except KeyboardInterrupt:
    app.quit()

if __name__ == "__main__":
  main()
