#!/usr/bin/env python3
# compute the (set theoretic) difference between two directories:
# i.e. files in A that are not in B

from glob import glob
import sys,os.path
args = sys.argv[1:]
lx = lambda t: t.split("/")[-1]
sx = lambda t: set(lx(x) for x in glob(t+"/*"))
if len(args) != 2:
  print("two args: A B -- computes A minus B")
  exit(1)
a = args[0]
b = args[1]
if os.path.isdir(a) and os.path.isdir(b): 
  sa = sx(a)
  sb = sx(b)
  dx = sa.difference(sb)
  dn = sa.intersection(sb)
  dy = sb.difference(sa)
  dxssdy = dx.issubset(dy)
  dyssdx = dy.issubset(dx)
  de = sa == sb
  #print("Lens {} {}".format(len(sa),len(sb)))
  # if de:
  #   #print("{} and {} are equal".format(a,b))
  # else:
  #   if dxssdy:
  #     #print("{} is contained in {}".format(a,b))
  #   if dyssdx:
  #     #print("{} is contained in {}".format(b,a))
  #print("Len {} {} {} -- equal? {}".format(len(dx),len(dy),len(dn),de))
  print("\n".join(dx))
else:
  print("Args must be directories")
  exit(2)
