#!/usr/bin/env python3

from glob import glob
import sys,os.path
args = sys.argv[1:]
lx = lambda t: t.split("/")[-1]
sx = lambda t: set(lx(x) for x in glob(t+"/*"))
if len(args) != 2:
    print("two args: A B -- computes A n B")
else:
    a = args[0]
    b = args[1]
    if os.path.isdir(a) and os.path.isdir(b): 
#         ax = glob(a+"/*")
#         bx = glob(b+"/*")
#         al = list(map(lx,ax))
#         bl = list(map(lx,bx))
#         sa = set(al)
#         sb = set(bl)
        sa = sx(a)
        sb = sx(b)
        dx = sa.intersection(sb)
        print("\n".join(dx))
    else:
        print("Args must be directories")
