#!/bin/bash

do_one() {
    local BD
    if [ -e "/dev/disk/by-label/$1" ]; then
        udisksctl mount -b "/dev/disk/by-label/$1" "${opts[@]}"
    elif BD="$(guessbd "$1")"; then
        fstype="$(lsblk -n -o FSTYPE "$BD")"
        echo Mounting "$BD"
        O=()
        if [ "$fstype" = "ntfs" ]; then
          O+=(noatime)
        fi
        if [ "${#O[@]}" -ne 0 ]; then
          opts=(-o "$(IFS=, ; echo "${O[*]}")")
        else
          opts=()
        fi
        udisksctl mount -b "$BD" "${opts[@]}"
    else
        echo Cannot mount "$1"
    fi
}

if [ $# = 0 ]; then
  lsblk -f | grep "^└─"
  exit
fi
for s; do do_one "$s"; done
