#!/usr/bin/env python3

import sys,re
args = sys.argv[1:]

d = {'s':1,'m':60,'h':60*60,'d':24*60*60}

if len(args) == 0:
    print(0)
else:
    a = args[0]
    if re.match(r"^\d+$",a):
        print(a)
    else:
        if re.match(r"\d",a[-1]):
            a += "s"
        b = list(filter(lambda t: len(t)>0,re.split(r"(\d+[dhms])",a)))
        s = 0
        for x in b:
            if not re.match(r"^\d+[dhms]$",x):
                print("Invalid {} ({})".format(a,x),file=sys.stderr)
            else:
                u = x[-1]
                if not u in d:
                    print("Invalid unit {} ({}})".format(u,x),file=sys.stderr)
                else:
                    s += int(x[:-1])*d[u]
        print(s)
