#!/usr/bin/perl

@s = ();
%f = ();
$total = 0;
sub tohms {
  my ($t) = @_;
  my ($d,$h,$m,$s);
  $s = $t % 60;
  $m = int($t / 60) % 60;
  $h = int($t / 3600) % 24;
  $d = int($t / (3600*24));
  my ($x);
  $x = "";
  if( $d ) { $x .= "${d}d";}
  if( $h ) { $x .= "${h}h";}
  if( $m ) { $x .= "${m}m";}
  if( $s ) { $x .= "${s}";}
  if( $x =~ /^$/ ) { $x = "0s"; }
  return $x;
}
sub fromhms {
  my ($hms) = @_;
  my ($hh,$mm,$ss,$h,$m,$s,$t);
  if( $hms =~ /^(\d+h)?(\d+m)?(\d+s?)?$/ ) {
    $hh = $1; $mm = $2; $ss = $3;
    $hh =~ s/h$//;
    $mm =~ s/m$//;
    $ss =~ s/s$//;
    $h = int($hh);
    $m = int($mm);
    $s = int($ss);
    $t = 3600*$h + 60*$m + $s;
    return $t;
  } else {
    return -1;
  }
}
for (@ARGV) {
  print(fromhms($_)."\n");
}
