#!/bin/bash
A="$1"
((s=A%60))
((A /= 60))
((m=A%60))
((A /= 60))
((h=A%24))
((A /= 24))
T=""
if (( A > 0 )); then T="$T${A}d"; fi
if (( h > 0 )); then T="$T${h}h"; fi
if (( m > 0 )); then T="$T${m}m"; fi
if (( s > 0 )); then T="$T${s}s"; fi
if [ -n "$T" ]; then echo "$T"; fi
